### ISSUE TITLE
Python2 depreciation

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/terminator#1]
Why add something to KCP that needs depreciated python2?  KaOS is very close to being complete python2 free, that will also result in removing all python2 related from KCP.
Make sure the app is not already ported to python3, even if it should be a development version (no dead project is NOT ported in some form).

**Comment by ErSoul** [comment]
I checked if terminator was ported to python3, but no... There's no more
development on it. But it is still very usable for my needs.

**Comment by demmm** [comment]
There are not 1 or 2 branches working on python3, there are multiple.....
https://code.launchpad.net/terminator/
Anyway, package will be broken again today with more python2 depends being removed from the repository.
